import assert from "node:assert/strict";
import { build } from "esbuild";
import { Window } from "happy-dom";

const built = await build({ entryPoints: ["webview/main.ts"], bundle: true, format: "iife", platform: "browser", write: false });
const window = new Window({ url: "https://webview.local/" });
const document = window.document;
document.body.innerHTML = '<div id="app"></div>';
const posted = [];
window.acquireVsCodeApi = () => ({ postMessage: m => posted.push(m), getState: () => undefined, setState: () => {} });
window.eval(built.outputFiles[0].text);
const host = data => window.dispatchEvent(new window.MessageEvent("message", { data }));
const status = { connected: true, streaming: false, compacting: false, retrying: false, restoring: false, modelLabel: "p/m", thinkingLevel: "off", statsText: "", sessionId: "attachment-session" };
host({ type: "snapshot", messages: [], state: null, status });
const input = document.querySelector("textarea");
const editText = (value, start = value.length, end = start) => {
 input.value = value; input.setSelectionRange(start, end); input.dispatchEvent(new window.Event("input", { bubbles: true }));
};
const paste = text => {
 const event = new window.Event("paste", { bubbles: true, cancelable: true });
 event.clipboardData = { files: [], getData: type => type === "text/plain" ? text : "" };
 input.dispatchEvent(event); return event;
};
const enter = () => input.dispatchEvent(new window.KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true }));
const clearPosts = () => { posted.length = 0; };
const large = "long pasted content\n".repeat(15);

editText("before SELECT after", 7, 13);
assert.equal(paste(large).defaultPrevented, true);
const created = posted.find(m => m.type === "createAttachment");
assert.ok(created, "long paste requests an owned host temporary file");
assert.equal(created.sessionId, status.sessionId);
assert.equal(created.attachment.text, large);
assert.equal(input.value, `before [${created.attachment.label}] after`, "long paste replaces selected text at the cursor");
assert.equal(input.value.slice(created.attachment.start, created.attachment.end), `[${created.attachment.label}]`);
clearPosts(); enter();
assert.equal(posted.filter(m => m.type === "prompt").length, 0, "pending attachment cannot send");
host({ type: "attachmentCreated", sessionId: "other", id: created.attachment.id });
enter(); assert.equal(posted.filter(m => m.type === "prompt").length, 0, "wrong-session completion cannot authorize send");
host({ type: "attachmentCreated", sessionId: status.sessionId, id: created.attachment.id });
clearPosts(); enter();
const sent = posted.find(m => m.type === "prompt");
assert.ok(sent, JSON.stringify({ posted, hint: document.querySelector(".composer-hint")?.textContent, value: input.value, disabled: input.disabled, errors: [...document.querySelectorAll(".pa-handler-error")].map(x => x.textContent), chips: document.querySelector(".composer-chips")?.innerHTML }));
assert.equal(sent.payload.attachments[0].id, created.attachment.id);
assert.equal(input.value, "");
assert.ok(document.querySelector(".working-row .working-mark"), "attachment preparation remains visibly pending without a cached user echo");
assert.equal(document.querySelectorAll(".user-message").length, 0, "attachment send waits for authoritative file contents rather than a cached echo");
host({ type: "promptRejected", clientRequestId: sent.payload.clientRequestId, error: "Save cancelled" });
assert.equal(input.value, sent.payload.text, "rejected file read/save restores the marker draft");
assert.equal(document.querySelectorAll(".composer-chips .compose-chip").length, 1, "rejected send restores attachment card");
clearPosts();
host({ type: "captureViewState", requestId: "attachment-transfer", sessionId: status.sessionId });
const captured = posted.find(m => m.type === "viewStateCaptured");
assert.ok(captured, JSON.stringify(posted));
assert.equal(captured.state.composer.draft.attachments[0].id, created.attachment.id);
host({ type: "releaseViewState", requestId: "attachment-transfer", sessionId: status.sessionId });
clearPosts(); enter();
const resent = posted.find(m => m.type === "prompt");
host({ type: "promptAccepted", clientRequestId: resent.payload.clientRequestId, recallText: "before EDITED FILE after" });
input.dispatchEvent(new window.KeyboardEvent("keydown", { key: "ArrowUp", bubbles: true, cancelable: true }));
assert.equal(input.value, "before EDITED FILE after", "recall uses host's latest saved contents, not original pasted snapshot");

host({ type: "snapshot", messages: [], state: null, status: { ...status, sessionId: "next-session" } });
clearPosts();
const short = paste("short");
assert.equal(short.defaultPrevented, false, "short text keeps native paste behavior");
assert.equal(posted.filter(m => m.type === "createAttachment").length, 0);
paste(large);
const late = posted.find(m => m.type === "createAttachment");
host({ type: "snapshot", messages: [], state: null, status: { ...status, sessionId: "third-session" } });
host({ type: "attachmentCreated", sessionId: "next-session", id: late.attachment.id });
assert.equal(input.value, "", "late completion does not insert content into another session");
assert.equal(document.querySelectorAll(".composer-chips .compose-chip").length, 0);
host({ type: "promptAccepted", clientRequestId: resent.payload.clientRequestId, recallText: "stale session text" });
input.dispatchEvent(new window.KeyboardEvent("keydown", { key: "ArrowUp", bubbles: true, cancelable: true }));
assert.equal(input.value, "", "late acceptance from a departed session cannot populate current history");
await window.happyDOM.close();
console.log("PASS attachment main integration: pending, session boundary, reject, transfer, latest recall, native short paste");
