import assert from "node:assert/strict";
import { createRequire } from "node:module";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
const require = createRequire(import.meta.url);
require("./vscode-stub.cjs");
const { SessionController } = require("../dist/controller.cjs");
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "brief-history-read-"));
const memory = new Map();
const context = () => {
 const state = { get: (k, d) => memory.get(k) ?? d, update: (k, v) => { memory.set(k, v); return Promise.resolve(); } };
 return { subscriptions: [], extensionUri: { fsPath: dir }, globalState: state, workspaceState: state };
};
const output = { append() {}, appendLine() {} };
const ctx = context();
const a = new SessionController(ctx, output), b = new SessionController({ ...ctx }, output);
const controllers = [a, b];
// History is refreshed explicitly below; do not connect to a real daemon on agent_end.
a.scheduleChildrenRefresh = () => {};
a.scheduleHistoryRefresh = () => {};
const file = path.join(dir, "done.jsonl");
const row = { id: "done", path: file, cwd: dir, timestamp: new Date(100).toISOString(), inWorkspace: true, status: "idle" };
const final = timestamp => ({ role: "assistant", stopReason: "stop", timestamp, content: [{type:"text",text:"done"}] });
const append = message => fs.appendFileSync(file, JSON.stringify({type:"message", message}) + "\n");
fs.writeFileSync(file, JSON.stringify({type:"session",id:"done",cwd:dir}) + "\n");
a.state = { sessionId: "done", sessionFile: file };
a.lastHistory = [row]; b.lastHistory = [row];
const posts = [];
b.attach({post: m => posts.push(m)});
try {
 append(final(100));
 await a.refreshHistoryCompletions([row]);
 assert.equal(a.historyCompletedAt.get(file), 100, "first scan records the existing completion baseline");
 assert.equal(a.historyUnreadComplete.has(file), false, "old completion is not new in this window");
 await b.refreshHistoryCompletions([row]);
 assert.equal(b.historyUnreadComplete.has(file), false, "another panel shares the same baseline");
 append(final(150));
 a.onAgentEvent({type:"agent_end", messages:[final(150)]});
 assert.equal(a.historyUnreadComplete.has(file), true, "background attachment must not acknowledge completion");
 assert.equal(b.lastHistory[0].unreadComplete, true, "completion repaints other controller caches");
 assert.ok(posts.some(m => m.type === "history" && m.sessions[0].unreadComplete));
 a.markHistorySessionOpened(file, 150);
 assert.equal(b.lastHistory[0].unreadComplete, false, "read receipt updates all views");
 b.decorateHistoryRow({...row,status:"running",running:true});
 b.decorateHistoryRow({...row,status:"inactive"});
 assert.equal(a.historyUnreadComplete.has(file), false, "old cache and unknown/offline cannot create a completion");
 a.markHistoryWaitingForUser(file, 200);
 a.markHistorySessionOpened(file, 100);
 assert.equal(a.historyUnreadComplete.has(file), true, "old rendered result cannot clear a newer result");
 a.markHistorySessionOpened(file, 200);
 await a.refreshHistoryCompletions([row]);
 b.overlayCachedHistory();
 assert.equal(a.historyUnreadComplete.has(file), false, "old completion replay and cached repaint cannot restore green");
 append(final(300));
 await b.refreshHistoryCompletions([row]);
 assert.equal(a.historyUnreadComplete.has(file), true, "missed entire fast turn is recovered from a newer terminal message");
 const sameWindow = new SessionController({ ...ctx }, output);
 controllers.push(sameWindow);
 assert.equal(sameWindow.historyUnreadComplete.has(file), true, "new panel with the same workspaceState shares notifications");
 assert.equal(sameWindow.historyCompletedAt, a.historyCompletedAt);
 assert.equal(sameWindow.historyReadAt, a.historyReadAt);
 const restored = new SessionController(context(), output);
 controllers.push(restored);
 assert.equal(restored.historyUnreadComplete.size, 0, "re-created window does not restore notifications from storage");
 assert.equal(restored.historyCompletedAt.size, 0, "completion markers are window-local");
 assert.equal(restored.historyReadAt.size, 0, "read cutoffs are window-local");
 await restored.refreshHistoryCompletions([row]);
 assert.equal(restored.historyUnreadComplete.has(file), false, "re-created window treats old completion as its baseline");
 assert.equal(a.historyUnreadComplete.has(file), true, "new-window scan cannot acknowledge another window's notification");
 a.updateHistoryRuntime(file, "running");
 assert.equal(a.historyUnreadComplete.has(file), false, "new running transition clears the previous notification");
 await b.refreshHistoryCompletions([row]);
 a.markHistoryWaitingForUser(file, 300);
 assert.equal(a.historyUnreadComplete.has(file), false, "disk and live replay cannot resurrect a cleared completion");
 a.updateHistoryRuntime(file, "idle");
 append({...final(310), stopReason:"aborted"});
 a.onAgentEvent({type:"agent_end", messages:[{...final(310), stopReason:"aborted"}]});
 await b.refreshHistoryCompletions([row]);
 assert.equal(a.historyUnreadComplete.has(file), false, "stopping without a newer terminal message is not completion");
 a.updateHistoryRuntime(file, "running");
 a.rowsFromCatalog([]);
 assert.equal(a.historyUnreadComplete.has(file), false, "missing runtime is not completion");
 const liveFile = path.join(dir, "live.jsonl");
 a.markHistoryWaitingForUser(liveFile, 350);
 assert.equal(a.historyUnreadComplete.has(liveFile), true, "first live completion counts without an earlier scan");
 const emptyFile = path.join(dir, "empty.jsonl");
 fs.writeFileSync(emptyFile, "");
 await a.refreshHistoryCompletions([{path:emptyFile}]);
 fs.appendFileSync(emptyFile, JSON.stringify({type:"message",message:final(360)})+"\n");
 await a.refreshHistoryCompletions([{path:emptyFile}]);
 assert.equal(a.historyUnreadComplete.has(emptyFile), true, "an empty first scan still establishes a baseline");
 // An unavailable file is not an empty transcript and cannot establish a baseline.
 const unavailableFile = path.join(dir, "unavailable.jsonl");
 await a.refreshHistoryCompletions([{path:unavailableFile}]);
 assert.equal(a.historyCompletedAt.has(unavailableFile), false, "failed read does not establish a zero baseline");
 fs.writeFileSync(unavailableFile, JSON.stringify({type:"message",message:final(370)})+"\n");
 await a.refreshHistoryCompletions([{path:unavailableFile}]);
 assert.equal(a.historyCompletedAt.get(unavailableFile), 370, "first successful read establishes the baseline");
 assert.equal(a.historyUnreadComplete.has(unavailableFile), false, "old transcript becoming readable is not a new completion");
 fs.appendFileSync(unavailableFile, JSON.stringify({type:"message",message:final(380)})+"\n");
 await a.refreshHistoryCompletions([{path:unavailableFile}]);
 assert.equal(a.historyUnreadComplete.has(unavailableFile), true, "new completion after a successful baseline is green");
 // A receipt may beat the first catalog scan. Retain its exact completion cutoff.
 const earlyFile = path.join(dir, "early.jsonl");
 fs.writeFileSync(earlyFile, JSON.stringify({type:"message",message:final(400)})+"\n");
 a.markHistorySessionOpened(earlyFile,400);
 await a.refreshHistoryCompletions([{...row,path:earlyFile}]);
 assert.equal(a.historyUnreadComplete.has(earlyFile), false, "late scanner cannot resurrect an already rendered result");
 a.updateHistoryRuntime(file,"running");
 a.sidecar=null;b.sidecar=null;
 const unreadBeforeDisconnect=a.historyUnreadComplete.has(file);
 a.onSidecarClosed();
 assert.equal(a.decorateHistoryRow(row).status,undefined,"last roster connection loss invalidates runtime, not completion");
 assert.equal(a.historyUnreadComplete.has(file),unreadBeforeDisconnect,"disconnect neither creates nor acknowledges a notification");
 const before = a.historyCompletedAt.get(file);
 fs.appendFileSync(file, JSON.stringify({type:"session_info",name:"renamed",timestamp:new Date().toISOString()})+"\n");
 await a.refreshHistoryCompletions([row]);
 assert.equal(a.historyCompletedAt.get(file),before,"rename does not create completion");
 a.awaitingInput=true;a.clearRunFlags();
 assert.equal(a.awaitingInput,false,"navigation clears old awaitingInput flag");
 // Discover completion before rank caps: this old row was previously invisible.
 const oldPath = path.join(dir, "capped.jsonl");
 fs.writeFileSync(oldPath, JSON.stringify({type:"message",message:final(9000)})+"\n");
 const catalog = Array.from({length:45},(_,i)=>({sessionId:`other-${i}`,sessionFile:path.join(dir,`missing-${i}.jsonl`),cwd:"/different-workspace",modified:new Date(1000+i).toISOString(),rosterStatus:"idle"}));
 catalog.push({sessionId:"capped",sessionFile:oldPath,cwd:"/different-workspace",modified:new Date(1).toISOString(),rosterStatus:"idle"});
 a.historySortMs.set(oldPath,1);
 a.ensureSidecar=async()=>({});a.listSessions=async()=>catalog;
 const baseline = await a.collectHistory();
 assert.equal(a.historyCompletedAt.get(oldPath),9000,"even capped rows receive a first-scan baseline");
 assert.equal(a.historyUnreadComplete.has(oldPath),false,"first discovery of a capped old completion is not green");
 assert.equal(baseline.some(r=>r.path===oldPath),false,"old row remains below the rank cap before a new completion");
 fs.appendFileSync(oldPath, JSON.stringify({type:"message",message:final(10000)})+"\n");
 const recovered = await a.collectHistory();
 assert.ok(recovered.some(r=>r.path===oldPath && r.unreadComplete),"old capped session re-enters history after external completion");
 assert.equal(recovered[0].path,oldPath,"recovered completion is ranked immediately");
 // An unsuccessful open is not a read receipt.
 a.markHistoryWaitingForUser(file,500);
 a.connectDaemon=async()=>{throw new Error("offline")};
 a.resolveHistorySession=async()=>row;
 a.showErrorNotice=()=>{};
 await a.switchSession(file,"done");
 assert.equal(a.historyUnreadComplete.has(file),true,"failed attach does not acknowledge unread");
 console.log("history read/completion tests passed");
} finally { for (const controller of controllers) controller.dispose(); fs.rmSync(dir,{recursive:true,force:true}); }
