import assert from "node:assert/strict";
import { createRequire } from "node:module";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
const require = createRequire(import.meta.url);
require("./vscode-stub.cjs");
const { SessionController } = require("../dist/controller.cjs");
const dir = fs.mkdtempSync(path.join(os.tmpdir(), "brief-history-read-"));
const memory = new Map();
const context = () => {
 const state = { get: (k, d) => memory.get(k) ?? d, update: (k, v) => { memory.set(k, v); return Promise.resolve(); } };
 return { subscriptions: [], extensionUri: { fsPath: dir }, globalState: state, workspaceState: state };
};
const output = { append() {}, appendLine() {} };
const ctx = context();
const a = new SessionController(ctx, output), b = new SessionController(ctx, output);
// History is refreshed explicitly below; do not connect to a real daemon on agent_end.
a.scheduleChildrenRefresh = () => {};
a.scheduleHistoryRefresh = () => {};
const file = path.join(dir, "done.jsonl");
const row = { id: "done", path: file, cwd: dir, timestamp: new Date(100).toISOString(), inWorkspace: true, status: "idle" };
const final = timestamp => ({ role: "assistant", stopReason: "stop", timestamp, content: [{type:"text",text:"done"}] });
const append = message => fs.appendFileSync(file, JSON.stringify({type:"message", message}) + "\n");
fs.writeFileSync(file, JSON.stringify({type:"session",id:"done",cwd:dir}) + "\n");
a.state = { sessionId: "done", sessionFile: file };
a.lastHistory = [row]; b.lastHistory = [row];
const posts = [];
b.attach({post: m => posts.push(m)});
try {
 append(final(100));
 a.onAgentEvent({type:"agent_end", messages:[final(100)]});
 assert.equal(a.historyUnreadComplete.has(file), true, "background attachment must not acknowledge completion");
 assert.equal(b.lastHistory[0].unreadComplete, true, "completion repaints other controller caches");
 assert.ok(posts.some(m => m.type === "history" && m.sessions[0].unreadComplete));
 a.markHistorySessionOpened(file, 100);
 assert.equal(b.lastHistory[0].unreadComplete, false, "read receipt updates all views");
 b.decorateHistoryRow({...row,status:"running",running:true});
 b.decorateHistoryRow({...row,status:"inactive"});
 assert.equal(a.historyUnreadComplete.has(file), false, "old cache and unknown/offline cannot create a completion");
 a.markHistoryWaitingForUser(file, 200);
 a.markHistorySessionOpened(file, 100);
 assert.equal(a.historyUnreadComplete.has(file), true, "old rendered result cannot clear a newer result");
 a.markHistorySessionOpened(file, 200);
 a.resolveHistorySession = async () => row;
 await a.markHistoryUnread(file, "done");
 await a.refreshHistoryCompletions([row]);
 b.overlayCachedHistory();
 assert.equal(a.historyUnreadComplete.has(file), true, "manual unread survives old completion replay and cached repaint");
 assert.equal(a.decorateHistoryRow({...row,status:"running",running:true}).unreadComplete, true, "running does not destroy manual unread");
 a.markHistorySessionOpened(file, 200);
 append(final(300));
 await b.refreshHistoryCompletions([row]);
 assert.equal(a.historyUnreadComplete.has(file), true, "missed entire fast turn is recovered from terminal message");
 const restored = new SessionController(context(), output);
 assert.equal(restored.historyUnreadComplete.has(file), true, "unread completion persists across controller reload");
 restored.markHistorySessionOpened(file, 300);
 await restored.refreshHistoryCompletions([row]);
 assert.equal(restored.historyUnreadComplete.has(file), false, "reload/read does not rediscover old completion as new");
 restored.dispose();
 // A receipt may beat the first catalog scan. Retain its exact completion cutoff.
 const earlyFile = path.join(dir, "early.jsonl");
 fs.writeFileSync(earlyFile, JSON.stringify({type:"message",message:final(400)})+"\n");
 a.markHistorySessionOpened(earlyFile,400);
 await a.refreshHistoryCompletions([{...row,path:earlyFile}]);
 assert.equal(a.historyUnreadComplete.has(earlyFile), false, "late scanner cannot resurrect an already rendered result");
 a.historyRuntime.set(file,{status:"running"});
 a.sidecar=null;b.sidecar=null;
 const unreadBeforeDisconnect=a.historyUnreadComplete.has(file);
 a.onSidecarClosed();
 assert.equal(a.decorateHistoryRow(row).status,undefined,"last roster connection loss invalidates runtime, not completion");
 assert.equal(a.historyUnreadComplete.has(file),unreadBeforeDisconnect,"disconnect neither creates nor acknowledges a notification");
 const before = a.historyCompletedAt.get(file);
 fs.appendFileSync(file, JSON.stringify({type:"session_info",name:"renamed",timestamp:new Date().toISOString()})+"\n");
 await a.refreshHistoryCompletions([row]);
 assert.equal(a.historyCompletedAt.get(file),before,"rename does not create completion");
 a.awaitingInput=true;a.clearRunFlags();
 assert.equal(a.awaitingInput,false,"navigation clears old awaitingInput flag");
 // Discover completion before rank caps: this old row was previously invisible.
 const oldPath = path.join(dir, "capped.jsonl");
 fs.writeFileSync(oldPath, JSON.stringify({type:"message",message:final(9000)})+"\n");
 const catalog = Array.from({length:45},(_,i)=>({sessionId:`other-${i}`,sessionFile:path.join(dir,`missing-${i}.jsonl`),cwd:"/different-workspace",modified:new Date(1000+i).toISOString(),rosterStatus:"idle"}));
 catalog.push({sessionId:"capped",sessionFile:oldPath,cwd:"/different-workspace",modified:new Date(1).toISOString(),rosterStatus:"idle"});
 a.historySortMs.set(oldPath,1);
 a.ensureSidecar=async()=>({});a.listSessions=async()=>catalog;
 const recovered = await a.collectHistory();
 assert.ok(recovered.some(r=>r.path===oldPath && r.unreadComplete),"old capped session re-enters history after external completion");
 assert.equal(recovered[0].path,oldPath,"recovered completion is ranked immediately");
 // An unsuccessful open is not a read receipt.
 a.historyUnreadComplete.add(file);
 a.connectDaemon=async()=>{throw new Error("offline")};
 a.resolveHistorySession=async()=>row;
 a.showErrorNotice=()=>{};
 await a.switchSession(file,"done");
 assert.equal(a.historyUnreadComplete.has(file),true,"failed attach does not acknowledge unread");
 console.log("history read/completion tests passed");
} finally { a.dispose(); b.dispose(); fs.rmSync(dir,{recursive:true,force:true}); }
