import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { build } from "esbuild";
import { Window } from "happy-dom";

const manifest = JSON.parse(readFileSync("package.json", "utf8"));
const command = manifest.contributes.commands.find(item => item.command === "brief.stashDraft");
assert.equal(command.title, "Stash / Restore Draft");
assert.equal(command.category, "Brief");
const binding = manifest.contributes.keybindings.find(item => item.command === command.command);
assert.equal(binding.key, "ctrl+k ctrl+alt+s");
assert.equal(binding.mac, "cmd+k cmd+alt+s");
assert.equal(binding.when, "brief.composerFocus && !editorTextFocus", "both sidebar and editor use composer focus, not active editor panel");
assert.match(readFileSync("src/extension.ts", "utf8"), /command\("brief\.stashDraft", \(\) => panels\.stashOrRestoreDraft\(\)\)/);

const built = await build({ entryPoints: ["webview/main.ts"], bundle: true, format: "iife", platform: "browser", write: false });
const window = new Window({ url: "https://webview.local/" });
const document = window.document;
document.body.innerHTML = '<div id="app"></div><button id="outside">Outside composer</button>';
let focused = true;
document.hasFocus = () => focused;
const posted = [];
window.acquireVsCodeApi = () => ({ postMessage: message => posted.push(message), getState: () => undefined, setState: () => {} });
window.eval(built.outputFiles[0].text);
const host = data => window.dispatchEvent(new window.MessageEvent("message", { data }));
const status = { connected: true, streaming: false, compacting: false, retrying: false, restoring: false, modelLabel: "p/m", thinkingLevel: "off", statsText: "", sessionId: "stash-session" };
const snapshot = sessionId => host({ type: "snapshot", messages: [], state: null, status: { ...status, sessionId } });
snapshot(status.sessionId);
const input = document.querySelector("textarea");
const text = value => { input.value = value; input.setSelectionRange(value.length, value.length); input.dispatchEvent(new window.Event("input", { bubbles: true })); };
const stash = () => host({ type: "stashOrRestoreDraft" });
const lastFocus = () => posted.filter(message => message.type === "composerFocusChanged").at(-1)?.focused;
input.focus();
assert.equal(lastFocus(), true);
text("first draft"); stash();
assert.equal(input.value, "", "shortcut stashes the focused draft");
stash();
assert.equal(input.value, "first draft", "shortcut restores through the same composer operation");
stash(); text("second draft"); stash();
assert.equal(input.value, "second draft", "occupied stash never overwrites either draft");
stash(); assert.equal(input.value, "second draft");
const toolbarButton = document.querySelector(".composer-card button:not([disabled])");
assert.ok(toolbarButton);
toolbarButton.focus();
assert.equal(lastFocus(), false, "toolbar is not composer input focus");
stash(); assert.equal(input.value, "second draft", "toolbar focus does not mutate the draft");
document.querySelector("#outside").focus();
assert.equal(lastFocus(), false);
stash(); assert.equal(input.value, "second draft", "host command does not mutate an unfocused composer");
input.focus(); focused = false; window.dispatchEvent(new window.Event("blur"));
assert.equal(lastFocus(), false);
stash(); assert.equal(input.value, "second draft", "background webview cannot stash");
focused = true; window.dispatchEvent(new window.Event("focus"));
assert.equal(lastFocus(), true);

// Stashes remain with the session when the sidebar switches sessions.
snapshot("another-session");
text("other draft"); stash();
snapshot(status.sessionId); stash();
assert.equal(input.value, "first draft", "returning to a session restores its own stash");
snapshot("another-session"); stash();
assert.equal(input.value, "other draft", "sidebar sessions keep separate stash slots");

text("/stash");
input.dispatchEvent(new window.KeyboardEvent("keydown", { key: "Enter", bubbles: true, cancelable: true }));
assert.equal(input.value, "", "slash command stashes previous draft through shared operation");
stash();
assert.equal(input.value, "other draft", "shortcut restores a slash-command stash");
text("/model literal draft"); stash();
assert.equal(input.value, "", "shortcut stashes slash-looking draft literally");
stash(); assert.equal(input.value, "/model literal draft");
host({ type: "setHistoryMode", enabled: true });
assert.equal(lastFocus(), false, "hidden composer resets the shortcut context");
stash(); assert.equal(input.value, "/model literal draft", "history-only view cannot receive stash");
assert.equal(posted.filter(message => message.type === "prompt").length, 0, "stash never sends a prompt");
await window.happyDOM.close();
console.log("PASS stash shortcut: contribution, focus guard, occupied stash safety, slash parity, per-session sidebar stash");
